// LOCAL HOST
### Get all users
GET http://localhost:8080/users

### Get one user
GET http://localhost:8080/users/69239de283a8dac6864f0c0b

### Create a user
POST http://localhost:8080/users HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "firstName": "Janet",
    "lastName": "Jackson",
    "email": "janetjackson@umail.com",
    "age": 55,
    "isActive": true,
    "role": "user",
    "createdAt": "2025-01-12T11:15:00Z",
    "address": {
        "street": "11 Jarvis Street",
        "city": "Colorado Springs",
        "state": "CO",
        "zip": "80903"
    }
}


### Update a user
PUT http://localhost:8080/users/69239de283a8dac6864f0c0b HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "firstName": "Sophia",
    "lastName": "Lee",
    "email": "sophialee@example.com",
    "age": 18,
    "isActive": true,
    "role": "admin",
    "createdAt": "2025-01-12T10:15:00Z",
    "address": {
        "street": "419 Wall Street",
        "city": "New York",
        "state": "NY",
        "zip": "10005"
    }
}

### Delete a user
DELETE http://localhost:8080/users/69239de283a8dac6864f0c0b


// PRODUCTION
### Get all users
GET https://project2-cse341-ziaf.onrender.com/users

### Get one user
GET https://project2-cse341-ziaf.onrender.com/users/69239de283a8dac6864f0c0b

### Create a user
POST https://project2-cse341-ziaf.onrender.com/users/users

### Update a user
PUT https://project2-cse341-ziaf.onrender.com/users/69239de283a8dac6864f0c0b

### Delete a user
DELETE https://project2-cse341-ziaf.onrender.com/users/69239de283a8dac6864f0c0b
